main/audio.js, main/index.js, main/ipc.js, main/menu.js, main/player.js, package.json, renderer/audio.html, renderer/audio.js, renderer/css/index.css, renderer/index.html, renderer/index.js, renderer/lib/config.js, renderer/lib/library.js, renderer/models/player.js, renderer/views/components/player.js, renderer/views/components/table.js
Audio is now in a separate process. Play/plause/volume are controlled via IPC.
I did a couple extra things besides moving audio out of the main renderer, mostly for the sake of code organization. Lots of inspiration taken from webtorrent-desktop.
@bcomnes please take a look when you have a minute! It's a big one.
> resolves #18
=> move audio to hidden process

renderer/css/base.css, renderer/views/components/button.js, renderer/views/components/player.js, renderer/views/components/search.js, renderer/views/components/toolbar.js, renderer/views/components/volume.js
Closes https://github.com/hypermodules/hyperamp/issues/69
I also removed the * selectors.  Weirdly, I personally prefer applying border-box selectively. You cool with that @ungoldman ?
=> Implement Button groups

main/player.js, renderer/css/base.css, renderer/css/index.css, renderer/css/range.css, renderer/css/scrollbar.css, renderer/css/variables.css, renderer/views/components/button.js, renderer/views/components/form-control.js, renderer/views/components/search.js, renderer/views/components/table.js, renderer/views/components/title.js, renderer/views/components/toolbar.js, renderer/views/preferences.js
Did some work on range and table. Starting to look alright.
=> improve range and table styles

renderer/css/base.css, renderer/css/range.css, renderer/views/components/button.js, renderer/views/components/search.js, renderer/views/components/toolbar.js
I'm going to go ahead and trust you on this one.  I don't have a very good argument the more I think about it.
=> put the * selector back

renderer/views/components/search.js, renderer/views/components/table.js
=> fix search, add album sort, tweak th style

renderer/views/components/search.js
This gives a little x in the right corner of the field when typing, just like iTunes.
=> Use search field instead of text input

.travis.yml, package.json, test/index.js
This is just a baseline for firing up the app and running spectron test.
=> Spectron tests

renderer/views/components/toolbar.js, renderer/views/preferences.js
=> Update file adding UI

main/audio.js, renderer/elements/player/index.js, renderer/elements/table/index.js, renderer/index.js, renderer/models/player.js, renderer/pages/main/index.js
This does some basic state capture on the main thread and enables next prev buttons.  Next up, playing the next song in the queue.
=> basic state management between threads

renderer/elements/table/index.js, renderer/models/library.js
This moves the sorting function into state so we only do it when adding new tracks.
=> move sorting function into state

renderer/css/range.css, renderer/elements/button/styles.js, renderer/elements/footer/index.js, renderer/elements/footer/styles.js, renderer/elements/volume/index.js, renderer/elements/volume/styles.js, renderer/models/player.js
- fix mute icon now working
- add disabled range style
- fix position action (undefined action throws an error that kills choo)
=> Misc fixes

main/menu.js, package.json, package.json.orig, test/index.js
Use a versioned default menu instead of copy pasta.
=> use electron-default-menu

main/index.js, package.json, renderer/audio.js, renderer/elements/table/index.js, renderer/models/player.js
closes #101
Basically this separates out queuing, playing and advancing which track is playing.
=> Implement queue 

main/config.js, main/index.js, main/player.js, package.json, renderer/audio.js, renderer/elements/footer/index.js, renderer/elements/volume/index.js, renderer/index.js, renderer/models/library.js, renderer/models/player.js
Adds a bunch of message passing and state control.  Pretty messy, but a step in the right direction.
=> State sync

main/index.js
Closes https://github.com/hypermodules/hyperamp/issues/115
=> fix borked message passing

renderer/elements/table/index.js, renderer/elements/table/styles.js, renderer/stores/player.js
=> add select, double click behavior to list items

main/player.js, package.json, renderer/css/base.css, renderer/css/range.css, renderer/css/scrollbar.css, renderer/css/variables.css, renderer/elements/button/styles.js, renderer/elements/footer/index.js, renderer/elements/footer/styles.js, renderer/elements/form/styles.js, renderer/elements/header/index.js, renderer/elements/header/styles.js, renderer/elements/playback/index.js, renderer/elements/playback/styles.js, renderer/elements/search/index.js, renderer/elements/search/styles.js, renderer/elements/table/index.js, renderer/elements/table/styles.js, renderer/elements/volume/index.js, renderer/elements/volume/styles.js, renderer/pages/main/index.js, renderer/pages/preferences/index.js, renderer/pages/styles.js, test/index.js, yarn.lock
still very WIP. I think it's looking pretty good though
=> experimental alternate layout & style

renderer/elements/footer/index.js, renderer/elements/footer/styles.js, renderer/elements/header/index.js, renderer/elements/player/index.js, renderer/elements/player/styles.js, renderer/elements/range/index.js, yarn.lock
This was the component I made that conflicted with the recent style updates, fully implemented with the recent style updates.
=> Implement player buttons component

renderer/elements/footer/index.js, renderer/elements/header/index.js, renderer/pages/main/index.js, renderer/pages/preferences/index.js
=> Make the 'footer' a component

renderer/elements/table/rows.js
Closes https://github.com/hypermodules/hyperamp/issues/175
=> Fix highlight on scroll.. Mostly

renderer/audio/audio-player.js
Closes https://github.com/hypermodules/hyperamp/issues/200
=> Properly encode file URLs in audio process

package.json, renderer/index.js
Closes https://github.com/hypermodules/hyperamp/issues/211
=> Add choo-expose

renderer/audio/audio-player.js, renderer/elements/header/index.js, renderer/elements/player/artwork.js
A few fixes for showstoppers on windows.
=> windows fixes

package.json, renderer/elements/header/index.js, renderer/elements/header/search.js, renderer/elements/player/artwork.js, renderer/elements/player/controls.js, renderer/elements/player/index.js, renderer/elements/player/meta.js, renderer/elements/player/volume.js, renderer/elements/playlist/index.js, renderer/elements/playlist/rows.js, renderer/elements/range/index.js
nanocomponent 6.0.0-1 isn't released yet, but you can link it to test it out.  This is mainly to see how hard the chagnes are to make.
=> Testing proposed nc 6.0.0-1 changes

renderer/elements/playlist/index.js, renderer/elements/playlist/rows.js, renderer/elements/playlist/styles.js
https://twitter.com/hyperampapp/status/907760599983022080
=> Sticky headers

renderer/elements/playlist/styles.js, renderer/elements/playlist/track-view.js, renderer/stores/library.js
added some fixes and some features
notable:
enter to play selected
esc to deselect
fix off-by-1 playlist error
fix off-by-1 error for down kbd shorcut
make table header an app drag region cause it looks like it should be atm
=> kbd shrtcts

renderer/elements/playlist/track-view.js
This removes underscores from the scroller, the first part of a refactor I've wanted to do.
=> Remove _’s

readme.md
already says IRC in the table header above, and freenode in lowercase looks better ;P
=> docs(readme): update irc badge

package.json
Closes https://github.com/hypermodules/hyperamp/issues/189
=> Add engines field

main/index.js, package.json, renderer/audio/index.js, renderer/index.js
adds IPC logging to all processes for better deep thoughts about IPC
=> add ipc logging

main/lib/artwork-cache/util.js
I think this will fix our race condition.
=> Fix race condition (maybe)

main/index.js
Add some auto update events that we should do more with at some point.
=> Add auto updater events

renderer/elements/playlist/index.js
=> Fix top level update function

CHANGELOG.md, main/index.js
Fix some lifecycle bugs on windows.
=> Fix windows lifecycle

main/index.js, package.json, renderer/audio.html, renderer/index.html, sentry.js
Closes https://github.com/hypermodules/hyperamp/issues/176
=> Add sentry

CHANGELOG.md, renderer/index.html
This should disable those annoying errors till we track down the source of them.
=> Disable nanotiming

main/index.js, main/track-dict.js
@ungoldman does this speed up scanning for you? Or is it still slow.
=> disable duration extraction

renderer/elements/header/styles.js
Resolves #282.
Selecting text in the search bar should now be... less of a drag 😎
=> fix(header): make search bar not draggable (#282)

main/lib/audio-library/filter.js, renderer/player/elements/playlist/styles.js, renderer/player/elements/playlist/track-view.js, renderer/player/lib/constants.js
Added genres to columns and search for @zeke, because why not.
=> LET THERE BE GENRES

main/index.js
=> feat(player): pause playback when waking from sleep

main/menu.js, main/windows/player.js
=> feat(player): add always-on-top view menu item

CHANGELOG.md, main/index.js, main/windows/audio.js, main/windows/player.js, package.json, renderer/audio/index.html, renderer/audio/loader.js, renderer/player/index.html, renderer/player/loader.js
Upgrade to electron 3 and add CSP
=> Electron3 + CSP
