hypermodules/hyperamp

- renderer/css/base.css
- renderer/css/variables.css
- renderer/index.js
- renderer/views/components/button.js
- renderer/views/components/form-control.js
- renderer/views/components/icon.js
- renderer/views/components/player.js
- renderer/views/components/toolbar.js
- renderer/views/components/volume.js
- renderer/views/preferences.js
Also changed a couple function signatures to have named options so that things are more optional/obvious. Added an optional `children`-style parameter to button to allow for text (or anything else).
> fix preferences view

- renderer/views/components/table.js
This is the least hacky way I could find to do this.  I looked at
- https://jsfiddle.net/purmou/npdob14y/4/
- https://codepen.io/tjvantoll/pen/JEKIu
We can probably use colgroup to set state sanely between the two tables
but we might not even have to because they seem to be tracking the same
widths.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
- https://docs.webplatform.org/wiki/html/elements/colgroup
closes https://github.com/hypermodules/hyperamp/issues/17
Also, it looks like overflow results in a slight x axis scroll amount.  A little janky.
> Sticky headers

- main/audio.js
- renderer/audio.js
This has a few bugs around initial start, but I can clean those up when we persist the play state to disk on quit, and load it back on launch.
> advance playback when ended

- main/player.js
- package.json
Closes https://github.com/hypermodules/hyperamp/issues/90
This remembers the player window when you close it and open it.  Eventually should probably save it on quit, but for now this is better than before.
> manage window state on player

- package-lock.json
- renderer/audio/audio-player.js
- renderer/elements/footer/index.js
- renderer/elements/footer/styles.js
- renderer/elements/meta/index.js
- renderer/elements/meta/styles.js
- renderer/elements/table/styles.js
This fixes whitespace dom flapping.  It looks like having the scroll bars intersect the scroll bar causes repaint on the scroll bar.  One fix would be to not have these intersect on an x-y perpendicular axis (e.g. put the sliders parallel below or above the table) but its probably not that big of a deal.
I kind of want to go back to that arrangement anyway since horizontal space is super valuable and we eat up a lot with the player controls. 
The main issue I think this solves is that it re-adds https://developer.mozilla.org/en-US/docs/Web/CSS/will-change which prevents painting on scrolling. 
Closes https://github.com/hypermodules/hyperamp/issues/173
> Fix reflow

- main/index.js
- main/lib/artwork-cache/index.js
- package.json
Removes the level dependency.  We should be caching these things in the main music DB anyway.
> Remove level dependency

- main/index.js
- main/library.js
- package.json
- renderer/elements/table/index.js
- renderer/elements/table/lib.js
- renderer/elements/table/rows.js
- renderer/elements/table/styles.js
- renderer/elements/table/test.js
This improves sorting of songs.  Its a fixed sort by album currently. When we have a better data model, we can do grouped albums by artist by year.
> Better sort

- main/index.js
- package.json
- renderer/elements/player/index.js
- renderer/elements/player/styles.js
- renderer/stores/player.js
This is a super simple shuffle mode.  Similar to https://github.com/hypermodules/hyperamp/issues/191, now playing state is not properly transformed between shuffle / sort modes.  I didn't have time to do a full proper implementation that would cover that use case, but this way you can at least filter and shuffle a music library.
> Implement naive shuffle

- package.json
- scripts/clear.js
Adds a script to clear config & persist stores in user data.
```
npm run clear
```
or
```sh
./scripts/clear.js # electron must be in PATH for this one to work
```
btw why do we have two different stores?
> add clear script

- renderer/elements/footer/index.js
Closes https://github.com/hypermodules/hyperamp/issues/196
It does introduce a bug though.  Because there is only one trackOrder
array, when we change the track order array, the metadata also get
updated, showing the wrong song info for whats playing.  It corrects on
the following queue, or if you restore whatever tracklist you had
before.
Fundamentally, we need to fix the data structure behind play queus and
the view state. We need to persist the active play state order, and only
activate a new play order state when a song is queued from a different
track order.
This issue is described more in https://github.com/hypermodules/hyperamp/issues/191
> Properly restore now-playing when window is closed

- main/index.js
- renderer/elements/header/index.js
- renderer/elements/header/styles.js
- renderer/stores/library.js
Contributes to the closing of https://github.com/hypermodules/hyperamp/issues/192 by passing main state to the main window.
@ungoldman I wasn't sure how the loader worked, but I suggest rebasing that branch to make sure you are using the latest deps.  I fixed some critical rendering bugs with cache-component.
> Propagate loading state to UI

- renderer/elements/loader/index.js
- renderer/elements/playlist/index.js
@bcomnes this PR shows the problem, which is still persisting for me. The cog spins when loading, but the playlist remains unchanged.
If you switch the line in `Playlist._render` from
```
if (this._loading) return loader()
```
to
```
return loader()
```
you get
so I'm guessing this is an `_update` method issue?
> attempt to add loader to playlist

- package.json
- renderer/elements/playlist/rows.js
Closes https://github.com/hypermodules/hyperamp/issues/213
Basically, we need to scroll to where we left off.  Probably need to reset scroll position if we change the underlying track list.
Try to break it!
> Fix scroll bug between nav

- package.json
- renderer/audio/audio-player.js
- renderer/audio/index.js
- renderer/index.html
- renderer/stores/config.js
- renderer/stores/library.js
- renderer/stores/player.js
Only emitting timeupdate events from audio when they are different from the last one. This way there is less unnecessary IPC communications, less unnecessary renders...
Also made the player logger a little nicer.
Also fiddled with initializing state in a couple stores.
Mostly just poking around and thinking about how to make the micro version of hyperamp we talked about a couple weekends ago.
> fix: omit duplicate timeupdate events

- renderer/elements/header/index.js
- renderer/elements/playlist/index.js
- renderer/elements/playlist/rows.js
- renderer/elements/playlist/styles.js
I spent a little time during lunch reworking the track list so it's a little more readable/usable at smaller window sizes.
I encountered an issue I didn't have time to track down though; the horizontal scroll doesn't work because of some CSS going on with (I think) the `.tableScrollWindow` element.
Also noticed the scrollbar height on horizontal is way different than the vertical one's width. Kind of like the chunkier one better though, easier to grab with the mouse.
> rework track list

- renderer/elements/header/index.js
- renderer/elements/playlist/track-view.js
- renderer/lib/constants.js
- renderer/stores/library.js
columns can now be toggled on and off
caveats:
- does not persist when window is closed (should be moved to `persist` state)
- widths are sometimes wonky, need to rethink table css again (i have an idea already)
> feat: make columns togglable

- main/windows/player.js
- package.json
- renderer/elements/player/artwork.js
- renderer/elements/player/controls.js
- renderer/index-dev.html
We need to get yo-yoify into the build process before we release.  @blahah released a nice transform that makes this work nicely in electron by prefixing require calls to built in to be `window.require` so that electron and other built in node calls still 'just work'.
- `npm start`: runs hyperamp in dev mode.  Uses buds for building a bundle without making a mess on disk.
- `npm run build`: builds hyperamp without any additional optimizations. Does not create DMG
- `npm run prod`: builds hyperamp with a few optimizations and creates a DMG.
Closes https://github.com/hypermodules/hyperamp/issues/174
> Enable browserify build process

- main/globalShortcuts.js
- main/index.js
When other applications steal the media key registration away from hyperamp, this will grab it back when you activate the window.
Closes https://github.com/hypermodules/hyperamp/issues/202
> Re-register media shortcuts when window activate

- main/index.js
- renderer/stores/library.js
When opening the window, scroll to the current index.  I had to re-differentiate between updating tract dicts and initializing.  Its a mess but we can revisit all of the event organization when we have time.
> Scroll to current index on window open

- CHANGELOG.md
- main/index.js
- renderer/elements/player/progress.js
- renderer/elements/playlist/index.js
- renderer/elements/playlist/track-view.js
- renderer/stores/library.js
Will close https://github.com/hypermodules/hyperamp/issues/238
Don’t run the children update functions twice, just optimistically render.
> Fixing state transfer bugs

- main/index.js
Emit auto update events on IPC
> Auto update ipc

- renderer/elements/player/progress.js
Fixes #270.
This fix appears to solve the progress indicator issue for me on my Windows box. But I have not tested on any other OS. 
On master, the progress indicator range input gets a `disabled="disabled"` attribute. After review, I noticed the `update` method pointed to a non-existing (stale?) state reference which would cause the `disabled` attribute to be attached.
I'm not sure why this would work on other OSes, but not on Windows. 🤷‍♂️
> Change state reference for progress indicator

- renderer/elements/playlist/track-view.js
Adds "Reveal in Finder" context menu option to tracks in the playlist.
Overrides `electron-context-menu`.
> feat(playlist): add "Reveal in Finder" context menu option to tracks

- main/lib/audio-library/sort.js
- package.json
Resolves #289.
This appears to resolve the bug where scanning a file with missing track/disk metadata causes a silent failure.
Tested locally on macOS Sierra.
> fix(scanning): uncaught TypeError from missing "no" prop (#289)

- main/lib/audio-library/sort.js
This fix should send tracks with no artist metadata to the end of the track dictionary.
Depends on #290.
> fix(sort): send tracks with no artist to bottom

- package.json
Fixed by bumping to `electron-builder@20.0.8`.
Packaged app tested locally with `npm run build`. "Report an issue" link now works fine.
Should be no breaking changes in `electron-builder` between `20.0.4` and `20.0.8`. 🤞 
See release notes: https://github.com/electron-userland/electron-builder/releases
> fix(menu): do not strip "bugs" from package (#304)
